### ISSUE TITLE
[Feature enhancement] More home page information and clearer sign in requirement 

### ISSUE THREAD

**Issue by spasion5023** [info442-spr22/b-team#86]
The site seems to be working well in both mobile and desktop versions! I would make it more evident to users that they need to log in either by bolding the text or displaying a log-in option in the center of the page. I wasn't quite sure what to do right away when I logged on to the page. On a related note, I think giving the user's a little more information about the website before they sign in might make the website more approachable as I wasn't really sure what to expect when I first saw the site.

**Comment by jeannechoi00** [comment]
- Will add more details/bolding in home page paragraph

**Comment by soshikun** [comment]
- Described the app more clearly: "The Better Educators forum is a resource in Washington State to help each other find technology equipment and resources for your students or your classroom"
- Also specified in the login page: "In order to access our website make sure you sign in with Google to Continue"
